### ISSUE TITLE
File type not supported? 

### ISSUE THREAD

**Issue by xi-pinmping** [TheWizardBear/terminal_images#5]
Hi, I set this up according to instruction and have deno added to my path correctly, but still when I try the test command I get an error. 

```
❯ terminal_images https://deno.land/images/hashrock_simple.png

error: Uncaught (in promise) Error: File type not supported.
    throw new Error("File type not supported.");
          ^
    at decodeImageFromRawFile (https://q5pm4pnchs74pdedmsydy4m2ibqanuqh4qsfdwlpd5y37miq.arweave.net/h17OP-aI8_v8eMg2SwPHGaQGAG0-gfkJFHZbx9xv7EQ/decode.ts:28:11)
    at decodeImageFromPath (https://q5pm4pnchs74pdedmsydy4m2ibqanuqh4qsfdwlpd5y37miq.arweave.net/h17OP-aI8_v8eMg2SwPHGaQGAG0-gfkJFHZbx9xv7EQ/decode.ts:14:16)
    at async getImageStrings (https://q5pm4pnchs74pdedmsydy4m2ibqanuqh4qsfdwlpd5y37miq.arweave.net/h17OP-aI8_v8eMg2SwPHGaQGAG0-gfkJFHZbx9xv7EQ/mod.ts:58:20)
    at async printImage (https://q5pm4pnchs74pdedmsydy4m2ibqanuqh4qsfdwlpd5y37miq.arweave.net/h17OP-aI8_v8eMg2SwPHGaQGAG0-gfkJFHZbx9xv7EQ/mod.ts:339:25)
    at async https://q5pm4pnchs74pdedmsydy4m2ibqanuqh4qsfdwlpd5y37miq.arweave.net/h17OP-aI8_v8eMg2SwPHGaQGAG0-gfkJFHZbx9xv7EQ/cli.ts:42:3

```
Any help greatly appreciated thanks!

**Comment by mjrlowe** [comment]
Hiya, sorry, the image url got changed. Try `terminal_images https://deno.land/images/artwork/hashrock_simple.png`. I'll update the docs with the correct url soon.
